'use strict';
const $=id=>document.getElementById(id);
const events={
 goal:{name:'Goal',icon:'⚽',color:'#dcf993',pattern:[450,180,450,180,450],description:'Three long pulses. A moment to celebrate.'},
 shot:{name:'Shot on target',icon:'◎',color:'#b3e5ff',pattern:[140,130,140],description:'Two short pulses. A chance on goal.'},
 yellow:{name:'Yellow card',icon:'🟨',color:'#ffe17d',pattern:[600],description:'One long pulse. A caution.'},
 red:{name:'Red card',icon:'🟥',color:'#ff857d',pattern:[600,200,600],description:'Two long pulses. A sending-off.'},
 substitution:{name:'Substitution',icon:'⇄',color:'#cbb5ff',pattern:[140,180,600],description:'Short, then long. A change on the pitch.'}
};
let haptics=true,demoTimer=null,demoRunning=false,pulseTimers=[],stream=null,context=null,frame=null,micState='off',micToken=0;
const bars=Array.from({length:40},()=>{const bar=document.createElement('i');$('meter').append(bar);return bar;});
const supportsHaptics=typeof navigator.vibrate==='function';
$('device-note').textContent=supportsHaptics?'Vibration requested on supported devices':'Visual pulses · vibration unavailable';
function cancelPulse(){pulseTimers.forEach(clearTimeout);pulseTimers=[];document.body.classList.remove('pulsing');if(supportsHaptics)navigator.vibrate(0);}
function pulse(pattern){cancelPulse();if(haptics&&supportsHaptics){const accepted=navigator.vibrate(pattern);if(!accepted)$('device-note').textContent='Vibration blocked · visual pulses active';}let time=0;pattern.forEach((duration,index)=>{pulseTimers.push(setTimeout(()=>document.body.classList.toggle('pulsing',index%2===0),time));time+=duration;});pulseTimers.push(setTimeout(()=>document.body.classList.remove('pulsing'),time));}
function showEvent(key){const event=events[key];document.documentElement.style.setProperty('--event-color',event.color);document.querySelectorAll('[data-event]').forEach(button=>button.classList.toggle('selected',button.dataset.event===key));$('moment-label').textContent='SIMULATED EVENT';$('moment-source').textContent='DEMO';$('moment-icon').textContent=event.icon;$('moment-title').textContent=event.name;$('moment-description').textContent=event.description;$('pulse-track').replaceChildren();event.pattern.filter((_,i)=>i%2===0).forEach(duration=>{const p=document.createElement('i');p.className=duration<300?'short':'long';$('pulse-track').append(p);});$('pulse-track').setAttribute('aria-label',event.description);pulse(event.pattern);$('history').querySelector('.empty')?.remove();const row=document.createElement('li');for(const [tag,value]of[['span',event.icon],['span',event.name],['small','DEMO · '+new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})]]){const cell=document.createElement(tag);cell.textContent=value;row.append(cell);}$('history').prepend(row);while($('history').children.length>10)$('history').lastChild.remove();}
function stopDemo(){clearTimeout(demoTimer);demoTimer=null;demoRunning=false;$('demo-icon').textContent='▶';$('demo-label').textContent='Play the five-event demo';}
document.querySelectorAll('[data-event]').forEach(button=>button.addEventListener('click',()=>{stopDemo();showEvent(button.dataset.event);}));
$('demo').addEventListener('click',()=>{if(demoRunning){stopDemo();cancelPulse();return;}stopMic();demoRunning=true;$('demo-icon').textContent='■';$('demo-label').textContent='Stop demo';const sequence=Object.keys(events);let index=0;function next(){if(!demoRunning)return;if(index>=sequence.length){stopDemo();return;}showEvent(sequence[index++]);demoTimer=setTimeout(next,2700);}next();});
$('haptics').addEventListener('click',()=>{haptics=!haptics;$('haptics').setAttribute('aria-pressed',String(haptics));$('haptics').textContent=haptics?'● Haptics on':'○ Haptics off';if(!haptics&&supportsHaptics)navigator.vibrate(0);});
$('clear').addEventListener('click',()=>{stopDemo();cancelPulse();$('history').replaceChildren();const li=document.createElement('li');li.className='empty';li.textContent='Your demo moments will appear here.';$('history').append(li);});
function stopMic(){micToken++;if(frame!==null)cancelAnimationFrame(frame);frame=null;stream?.getTracks().forEach(track=>track.stop());stream=null;if(context){context.close().catch(()=>{});context=null;}micState='off';$('listen').disabled=false;$('listen').setAttribute('aria-pressed','false');$('listen-label').textContent='LISTEN';$('mic-dot').classList.remove('active');$('sound-state').textContent='MIC OFF';$('sound-description').textContent='Tap Listen to see the sound around you.';$('mode').textContent='INTERACTIVE DEMO';bars.forEach(bar=>{bar.style.height='3px';bar.style.background='';});}
async function startMic(){stopDemo();cancelPulse();if(!navigator.mediaDevices?.getUserMedia){$('sound-description').textContent='Microphone unavailable. Open this page in a supported browser over HTTPS.';return;}const token=++micToken;micState='starting';$('listen').disabled=true;$('listen-label').textContent='WAIT';$('sound-description').textContent='Allow microphone access to display ambient sound level.';try{const captured=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});if(token!==micToken){captured.getTracks().forEach(track=>track.stop());return;}stream=captured;const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)throw new Error('Audio processing is unavailable.');context=new AudioContextClass();await context.resume();if(token!==micToken)return;const analyser=context.createAnalyser();analyser.fftSize=1024;context.createMediaStreamSource(stream).connect(analyser);const data=new Uint8Array(analyser.fftSize);micState='on';$('listen').disabled=false;$('listen').setAttribute('aria-pressed','true');$('listen-label').textContent='STOP';$('mic-dot').classList.add('active');$('mode').textContent='MICROPHONE PREVIEW';$('sound-state').textContent='LISTENING';$('sound-description').textContent='Live sound level only. No event recognition. Audio stays on your device.';for(const track of stream.getTracks())track.addEventListener('ended',()=>{if(token===micToken)stopMic();});function draw(){if(token!==micToken)return;analyser.getByteTimeDomainData(data);let sum=0;data.forEach(value=>{sum+=((value-128)/128)**2;});const level=Math.min(1,Math.sqrt(sum/data.length)*5);bars.forEach((bar,index)=>{const shape=.35+.65*Math.sin((index+1)/41*Math.PI);bar.style.height=(3+level*28*shape)+'px';bar.style.background=level>.05?'#dcf993':'';});frame=requestAnimationFrame(draw);}draw();}catch(error){if(token!==micToken)return;stopMic();$('sound-description').textContent=error.name==='NotAllowedError'?'Microphone permission was denied. You can still try all five demo events.':error.name==='NotFoundError'?'No microphone was found. You can still try the event demo.':'Could not start the microphone. Check browser permissions and try again.';}}
$('listen').addEventListener('click',()=>micState==='off'?startMic():stopMic());
$('help').addEventListener('click',()=>{$('help-dialog').showModal();});
$('close-help').addEventListener('click',()=>$('help-dialog').close());$('got-it').addEventListener('click',()=>$('help-dialog').close());
function suspend(){stopDemo();cancelPulse();stopMic();}
document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});window.addEventListener('pagehide',suspend);
